# Generated by Django 4.0.4 on 2022-05-15 02:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vol_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
