# Generated by Django 4.0.4 on 2022-05-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0002_alter_category_vol_list_alter_sentence_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
