# Generated by Django 4.0.4 on 2022-05-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0003_alter_sentence_word_delete_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ('word',)},
        ),
    ]
