# Generated by Django 4.0.4 on 2022-05-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0004_alter_sentence_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Latest_categories',
        ),
    ]
