# Generated by Django 4.0.4 on 2022-05-20 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vols', '0005_rename_category_latest_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('vol_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.DeleteModel(
            name='Latest_categories',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
